### ISSUE TITLE
Warmup and horizon effects validation

### ISSUE THREAD

**Issue by jwnorm** [misken/hillmaker#59]
Does it make sense to add a validation check to `make_hills` that determines the length of warmup and horizon effects based on a rule?

The rule could be based on some combination of LOS and the number of days in the supplied date range. As an example, I am imagining it would compute the 75th percentile of LOS and then automatically adjust the start and end date based on this number. If the date range is quite large, the adjustment can be multiplied by a factor of 5 or something.

The main driver behind this is that casual users of the application might not fully grasp the implication of these effects and providing that adjustment for them could avoid misleading data. Of course, users who fully understand the concepts of these effects could opt to adjust the date range manually and could turn off this functionality with a simple `validate_warmup_horizon_effects=False`.

**Comment by misken** [comment]
It is kind of wild that you just now added this issue. Literally, this morning I was digging up my old hillmaker paper and reviewing the heuristic based on transient analysis of infinite server queueing systems that I used to ballpark a warmup time. I'm not sure I've ever shared the paper with you. I'll email it along with a Jupyter notebook that just has the start of the documentation for this. Bottom line - yes we should add this. In a nutshell, the approximation (see Section 3.3.1 in the paper) just relies on the average length of stay and how close you want to get to steady state. The notebook has a quick graph. Alpha is percentage away from steady state.

**Comment by misken** [comment]
If you want to see how some of the docs are starting to come together, the work is happening in the `docs-1013` branch. Take a look at `getting_started`, `using_make_hills` and `using_oo_api` notebooks. I'm just trying to get some minimal docs going and we can always add more.
